In [1]:
import numpy as np
import json

from goForwardGame import vectorizedGoForwardGamesTest
from ga_neural_net import ANN

vectorizedGame = vectorizedGoForwardGamesTest()

In [2]:
vectorizedGame.reset()

In [3]:
players = []
for _ in range(4):
    players.append(ANN(layers_unit=[732, 1024, 1024, 1]))

In [4]:
EPOCH_GAME = 4 # Number of games before select best to crossover
for _ in range(10):
    scoreboard = np.zeros(4)
    for _ in range(EPOCH_GAME):
        vectorizedGame.reset()
        is_done = False
        with open('log.txt', 'a') as logfile:
            while not is_done:
                _, string_cards, actions, number_actions = vectorizedGame.info()
                current_player, state, action_space = vectorizedGame.getCurrentState()
                step = min(int(players[current_player-1].get_step(state[0]) * len(number_actions)), len(number_actions)-1)
                rewards, is_done, end_info = vectorizedGame.step(number_actions[step])
                logfile.write(str(number_actions[step])+'\t')
            logfile.write('\n')
            logfile.close()
        scoreboard += rewards
        print(rewards)
    print('After', EPOCH_GAME, 'scoreboard:', scoreboard/EPOCH_GAME)
    rank = scoreboard.argsort()[::-1]
    players[rank[2]] = players[rank[0]].fuck_with(players[rank[1]], 0.5)
    players[rank[3]] = players[rank[0]].fuck_with(players[rank[1]], 0.1)

[-13.  -8.  25.  -4.]
[-13.  -3.  18.  -2.]
[-9. -5. -3. 17.]
[-13.  -4.  21.  -4.]
After 4 scoreboard: [-12.    -5.    15.25   1.75]
[-13. -13.  28.  -2.]
[-13. -10.  25.  -2.]
[-13. -10.  26.  -3.]
[-13. -12.  36. -11.]
After 4 scoreboard: [-13.   -11.25  28.75  -4.5 ]
[-13.  -7.  23.  -3.]
[-13. -10.  27.  -4.]
[-13. -13.  28.  -2.]
[-13. -13.  30.  -4.]
After 4 scoreboard: [-13.   -10.75  27.    -3.25]
[ -4. -13.  26.  -9.]
[-13. -13.  28.  -2.]
[-10. -13.  25.  -2.]
[-13. -13. -12.  38.]
After 4 scoreboard: [-10.   -13.    16.75   6.25]
[-13. -13.  33.  -7.]
[-13.  -7.  33. -13.]
[-13. -11.  35. -11.]
[-13. -13.  27.  -1.]
After 4 scoreboard: [-13. -11.  32.  -8.]
[-13. -12.  27.  -2.]
[-13. -13.  30.  -4.]
[-13. -13.  30.  -4.]
[-13. -11.  33.  -9.]
After 4 scoreboard: [-13.   -12.25  30.    -4.75]
[-10. -13.  26.  -3.]
[-13. -13.  -1.  27.]
[-12. -13.  28.  -3.]
[ -4. -13.  23.  -6.]
After 4 scoreboard: [ -9.75 -13.    19.     3.75]
[-13. -13.  27.  -1.]
[-13. -10.  -2.  25.]
[-

In [7]:
# Export model
players[0].export_model('model.json')

In [8]:
# Load model from saved file
model = ANN.load_model('model.json')